### PR TITLE
Update main.yml

### PR DESCRIPTION
**Pull request by miloskroulik**
Make role work with Ansible 1.8 Similar issue at https://github.com/kosssi/ansible-role-composer/issues/14

### CODE REVIEW

**Comment by tersmitten** [comment]
adminer_install_dirs is defined in defaults/main.yml. I don't see what bug this fixes. Travis-ci does not fail for Ansible 1.8. Please explain yourself.

**Comment by miloskroulik** [comment]
Well, without this change, the role failed for me (trying to use it on Ubuntu 14.04). I will post the exact error message later.

**Comment by tersmitten** [comment]
@miloskroulik Can you post the exact message for me?

**Comment by miloskroulik** [comment]
Sorry, I will try to do it ASAP.

**Comment by tersmitten** [comment]
I removed the `when` because it's not needed anyway. I'm closing this ticket for now. Feel free to open a new ticket if your problem continues to exist

**Pull request closed without merging**
